export const SET_TODO_LIST = "SET_TODO_LIST";
export const ADD_TODO = "ADD_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const SORT_COMPLETED = "SORT_COMPLETED";
export const SORT_UNCOMPLETED = "SORT_UNCOMPLETED";
export const SORT_ASCENDING = "SORT_ASCENDING";
export const SORT_DESCENDING = "SORT_DESCENDING";
